In [2]:
import numpy as np
import pandas as pd

In [3]:
List1=[1,2,3,4,5]
List2=[6,7,8,9,10]
FL = List1+List2
FL

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
FL.reverse()
print(FL)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [5]:
Array1=np.array(List1)
Array2=np.array(List2)
Array1+Array2

array([ 7,  9, 11, 13, 15])

In [6]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
b=a.T
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
np.random.randint(1,5)

4

In [9]:
np.random.randint(1,5,4)

array([1, 2, 2, 4])

In [10]:
np.random.normal(5,3)

4.359758921664838

In [11]:
np.random.normal(5,3,4)

array([-1.14343584,  6.51155307,  3.90566147,  4.83062184])

In [12]:
np.random.normal(5,3,(2,2))

array([[ 4.24229694,  0.24956112],
       [ 5.08392143, 10.19333993]])

In [13]:
c=np.array([[0,992,855,423,803],[0,0,276,538,553],[0,0,0,217,561],[0,0,0,0,262],[0,0,0,0,0]])
c

array([[  0, 992, 855, 423, 803],
       [  0,   0, 276, 538, 553],
       [  0,   0,   0, 217, 561],
       [  0,   0,   0,   0, 262],
       [  0,   0,   0,   0,   0]])

In [18]:
sorted_c = np.sort(c, axis=None)
sorted_c

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 217, 262, 276, 423, 538, 553, 561, 803, 855, 992])

In [19]:
sorted_c_desc = np.sort(c, axis=None)[::-1]
sorted_c_desc

array([992, 855, 803, 561, 553, 538, 423, 276, 262, 217,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [14]:
d=c.T
d

array([[  0,   0,   0,   0,   0],
       [992,   0,   0,   0,   0],
       [855, 276,   0,   0,   0],
       [423, 538, 217,   0,   0],
       [803, 553, 561, 262,   0]])

In [15]:
c+d

array([[  0, 992, 855, 423, 803],
       [992,   0, 276, 538, 553],
       [855, 276,   0, 217, 561],
       [423, 538, 217,   0, 262],
       [803, 553, 561, 262,   0]])

In [16]:
e = c[0,2]/d[2,1]
e

3.097826086956522

In [17]:
if d[0, 2] != 0:  
    f = c[0, 2] / d[0, 2]  
    f
elif d[0, 2] == 0 and c[0, 2] != 0:  
    print("NA")
else:  
    print("0")

NA


In [21]:
for i in range(c.shape[0]): 
    for j in range(c.shape[1]): 
        if d[i, j] != 0:  
            result = c[i, j] / d[i, j]
            print(result)
        else:
            print("Wrong")

Wrong
Wrong
Wrong
Wrong
Wrong
0.0
Wrong
Wrong
Wrong
Wrong
0.0
0.0
Wrong
Wrong
Wrong
0.0
0.0
0.0
Wrong
Wrong
0.0
0.0
0.0
0.0
Wrong
